### PR TITLE
Fix deployment action and add ruff-bugbear

### PR DESCRIPTION
**Pull request by abkfenris**
Thanks @ocefpaf for the suggestions and the fact that I could swipe the actions config from erddapy.

Needed to tweak bugbear settings to play nice with FastAPI. https://github.com/charliermarsh/ruff/issues/389

### CODE REVIEW

**Comment by abkfenris** [comment]
@ocepaf, if I understand things right, that failed because there aren't any tags on the repo yet? https://github.com/xpublish-community/xpublish-opendap/actions/runs/4844988654/jobs/8633643309#step:5:21

**Comment by ocefpaf** [comment]
> @ocepaf, if I understand things right, that failed because there aren't any tags on the repo yet? https://github.com/xpublish-community/xpublish-opendap/actions/runs/4844988654/jobs/8633643309#step:5:21

Yep. Should work fine when you make one. In hindsight, we add these GHA in old projects and never realized it is, in a way, flawed for new ones without a tag.

**Comment by abkfenris** [comment]
Does twine or build need the tags?

**Comment by abkfenris** [comment]
I've disabled the workflow for now.

**Comment by ocefpaf** [comment]
> Does twine or build need the tags?

Nope. Just the start to get the tag but that blocks the other steps.

**Pull request merged**
