### PR TITLE
Bug Fix: Preventing failure when dataset contains a non-numerica data-variable

### PR DESCRIPTION
**Pull request by xaviernogueira**
Hi @abkfenris it is me again. I added a bug fix to allow a server to pass over a non-numeric data-variable without throwing an error.

Issue: If a dataset contains a non-numeric data-variable (for instance, [OSN data](https://www.openstoragenetwork.org/motivation/our-policy/) often has "name" stored as a dtype="U11" data-array), the code would look for "dtype" within `ds['non_numeric_var'].encoding` which would not exist. A KeyError would be raised, and the server would fail to serve any data.

Solution: I made a custom exception that inherits from KeyError (`NoEncodingDtype`) that is thrown in this specific case only (i.e., 'dtype' not in `ds[var]encoding.keys()`). If thrown, when the `dap.Grid` object is being built, a warning message is logged, and the non-numeric variable is skipped over.

All pre-commit hooks were passed, so this time it should go through without problems? Let me know if you want me to adjust anything.

### CODE REVIEW

**Comment by abkfenris** [comment]
Hi Xavier, any chance you could point me at a specific dataset, or make a test case? I'd like to make it keeps working that way in the future.

**Comment by xaviernogueira** [comment]
Sure. I attached one of the items from an Intake catalog where I encountered the issue, but it was present in the other OSN items as well.

```
  prism-v2-osn:
    driver: zarr
    description: "USGS THREDDS Holdings/Parameter-elevation Regressions on Independent Slopes Model Monthly Climate Data for the Continental United States"
    args:
      urlpath: 's3://rsignellbucket2/nhgf/sample_data/prism_v2.zarr'
      consolidated: true
      storage_options:
        anon: true
        requester_pays: false
        client_kwargs:
          endpoint_url: https://renc.osn.xsede.org
```

**Comment by abkfenris** [comment]
Hmm, I'm not seeing any name variables, and why it doesn't have an known conversion it doesn't throw an error because everything has a encoding dtype.

image
image

**Comment by xaviernogueira** [comment]
Ah I see. Figured out the source of the problem was on my side. Sorry about that!

**Pull request closed without merging**
